### PR TITLE
Option fixes

### LINKED ISSUE #49: Options testing for full games is broken
I noticed that using BENCHMARK_OPTIONS=true causes validation of the options, which are actually computed incorrectly (before this change). For some reason the tests seem to think that a unit can move via convoy to the same spot, and an army can move via convoy to a sea space. Also it's suggesting builds in non-SCs. This is never suggested in a real game, so I assume it's an issue with the test framework. I'll raise a separate bug for this.

As an example here's the output for the first Fall and Adjustment of test game 1 for the Hundred variant:

```
.../godip/variants/hundred$ env BENCHMARK_OPTIONS=true DEBUG=true go test -v ./...
=== RUN   TestGames
Testing Hundred game_1.txt
Checked 17 phases, executed 139 orders and asserted 525 positions in game_1.txt, found 0 failures.
Spent on average 605.497µs calculating options, never more than 2.011284ms.--- FAIL: TestGames (0.07s)
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order cal Move cal: ErrIllegalMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [cal eng]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [cal str]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [fla eng]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [fla str]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [brt str]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [brt eng]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [nom eng]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order lon Support [nom str]: ErrIllegalSupportMove
    games_testing.go:148: Wanted "England", got ""
    games_testing.go:151: got invalid order brt Move brt: ErrIllegalMove
    games_testing.go:148: Wanted "Burgundy", got ""
    games_testing.go:151: got invalid order fla Move fla: ErrIllegalMove
    games_testing.go:148: Wanted "France", got ""
    games_testing.go:151: got invalid order nom Move nom: ErrIllegalMove
    games_testing.go:148: Wanted "Burgundy", got ""
    games_testing.go:151: got invalid order Army Build fla: ErrMissingSupplyCenter
    games_testing.go:148: Wanted "Burgundy", got ""
    games_testing.go:151: got invalid order Fleet Build fla: ErrMissingSupplyCenter
    games_testing.go:148: Wanted "Burgundy", got ""
    games_testing.go:151: got invalid order Army Build hol: ErrMissingSupplyCenter
    games_testing.go:148: Wanted "Burgundy", got ""
    games_testing.go:151: got invalid order Fleet Build hol: ErrMissingSupplyCenter
    games_testing.go:148: Wanted "Burgundy", got ""
    games_testing.go:151: got invalid order Army Build lux: ErrMissingSupplyCenter
...
=== RUN   TestLondonCalais
--- PASS: TestLondonCalais (0.00s)
=== RUN   TestBuildAnywhere
--- PASS: TestBuildAnywhere (0.00s)
=== RUN   TestConvoy
--- PASS: TestConvoy (0.00s)
=== RUN   TestDisbandFrenchUnit
--- PASS: TestDisbandFrenchUnit (0.00s)
FAIL
FAIL	github.com/zond/godip/variants/hundred	0.077s
```

This is while testing this position:
https://www.vdiplomacy.com/map.php?gameID=33990&turn=0&mapType=large

### PR DESCRIPTION
**Pull request by tttppp**
Fixes #49.

Note that this includes an update of two of the Droidippy games to add coasts to orders.

### CODE REVIEW

File: orders/convoy.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ func (self *convoy) Options(v godip.Validator, nation godip.Nation, src godip.Pr
 	if !ok || convoyer.Type != godip.Fleet {
 		return
 	}
-	if v.Graph().Flags(actualSrc)[godip.Land] && !v.Graph().Flags(actualSrc)[godip.Convoyable] {
+	if v.Graph().Flags(actualSrc.Super())[godip.Land] && !v.Graph().Flags(actualSrc.Super())[godip.Convoyable] {
```
Comment (zond) [inline orders/convoy.go]: Is this safe? Do all super-provinces have the correct Land/Convoyable flags?

File: variants/pure/games_test.go [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+import (
+	"testing"
+
+	"github.com/zond/godip"
+
+	tst "github.com/zond/godip/variants/testing"
+)
+
+func init() {
+	godip.Debug = true
```
Comment (zond) [inline variants/pure/games_test.go]: You probably don't want this committed?

Comment (zond) [reply variants/pure/games_test.go]: Oh sorry, it was a test...

**Comment by zond** [comment]
LGTM!

File: orders/convoy.go (hunk 1 above)
Comment (tttppp) [reply orders/convoy.go]: Yes, I'm pretty sure they do.

The coast subprovinces only have Sea set because fleets are allowed there and armies aren't, and vice versa for the super provinces.

Comment (zond) [reply orders/convoy.go]: Alright then :)
